contexts:
- data:
    output_dir: hive-processed
    services_dir: hive-services
    templates_dir: hive-templates
  name: hive
- data:
    output_dir: aws-account-operator-processed
    services_dir: aws-account-operator-services
    templates_dir: aws-account-operator-templates
  name: aws-account-operator
- data:
    output_dir: certman-operator-processed
    services_dir: certman-operator-services
    templates_dir: certman-operator-templates
  name: certman-operator
current: hive
