contexts:
- data:
    output_dir: hive-processed
    services_dir: hive-services
    templates_dir: hive-templates
  name: hive
- data:
    output_dir: aws-account-operator-processed
    services_dir: aws-account-operator-services
    templates_dir: aws-account-operator-templates
  name: aws-account-operator
- data:
    output_dir: deadmanssnitch-operator-processed
    services_dir: deadmanssnitch-operator-services
    templates_dir: deadmanssnitch-operator-templates
  name: deadmanssnitch-operator
- data:
    output_dir: pagerduty-operator-processed
    services_dir: pagerduty-operator-services
    templates_dir: pagerduty-operator-templates
  name: pagerduty-operator
- data:
    output_dir: certman-operator-processed
    services_dir: certman-operator-services
    templates_dir: certman-operator-templates
  name: certman-operator
- data:
    output_dir: dedicated-admin-operator-processed
    services_dir: dedicated-admin-operator-services
    templates_dir: dedicated-admin-operator-templates
  name: dedicated-admin-operator
- data:
    output_dir: configure-alertmanager-operator-processed
    services_dir: configure-alertmanager-operator-services
    templates_dir: configure-alertmanager-operator-templates
  name: configure-alertmanager-operator
current: hive
