contexts:
- data:
    output_dir: hive-processed
    services_dir: hive-services
    templates_dir: hive-templates
  name: hive
- data:
    output_dir: aws-account-operator-processed
    services_dir: aws-account-operator-services
    templates_dir: aws-account-operator-templates
  name: aws-account-operator
- data:
    output_dir: deadmanssnitch-operator-processed
    services_dir: deadmanssnitch-operator-services
    templates_dir: deadmanssnitch-operator-templates
  name: deadmanssnitch-operator
- data:
    output_dir: pagerduty-operator-processed
    services_dir: pagerduty-operator-services
    templates_dir: pagerduty-operator-templates
  name: pagerduty-operator
current: hive
