services:
- hash: none
  name: managed-cluster-config
  path: /hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl 
  url: https://github.com/openshift/managed-cluster-config 
  hash_length: 7